version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./build/backend/Dockerfile
    volumes:
      - ./backend/src:/backend
    ports:
      - "8080:8080"
    command: ["air"]
